[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/store/:splat.js"
  to = "https://bit-bazaar-storefront.netlify.app/:splat.js"
  status = 200

[[redirects]]
  from = "/blog/:splat.js"
  to = "https://bit-bazaar-blog.netlify.app/:splat.js"
  status = 200