[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/store/*.js"
  to = "https://bit-bazaar-storefront.netlify.app/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/blog/*.js"
  to = "https://bit-bazaar-blog.netlify.app/:splat"
  force = true
  status = 200


[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
